### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by zcyyyy24** [elnino9ykl/OOSS#1]
Hi, @elnino9ykl 
What is the dependencies for this project? Is there any requirement.txt or .yaml? 
Hope you can help me.
Best regards.

**Comment by elnino9ykl** [comment]
Hi, thank you for your interest.

The dependencies include
Python >= 2.6
PyTorch >= 1.0.0

**Comment by zcyyyy24** [comment]
> Hi, thank you for your interest.
> 
> The dependencies include Python >= 2.6 PyTorch >= 1.0.0

Only need to install Python and Pytorch? Any other requirements?
