### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by zcyyyy24** [elnino9ykl/OOSS#2]
Hi, I have set the environment for the project and downloaded the dataset in the README. @elnino9ykl 
But I still can't run the eval_color.py successfully. There was no segmentation output, only load the pretrained weights, like below.
![image](https://github.com/elnino9ykl/OOSS/assets/152855926/98dfe521-f133-4149-956a-921d4d4c9953)
![image](https://github.com/elnino9ykl/OOSS/assets/152855926/41c6cbe6-9b4c-4aef-abef-cf8ad2738665)

**Comment by elnino9ykl** [comment]
Hi, thank you for the interest. Please check the path of the dataset.

As shown in this work, they can correctly run the model for producing segmentation.
https://arxiv.org/pdf/2203.13838.pdf
